# Chart module #7 for SEPH empl and AWE by ind, SA
# August 2, 2021
library(shiny)
library(shinyjs)
library(shinyWidgets)
library(tidyverse)

source("Tabl_specs.R")

Est1001 <- c(
  "Employment for all employees",                                
  "Average weekly earnings including overtime for all employees"
)
naics1001 <- c(
  "Industrial aggregate including unclassified businesses [00-91N]",                                                   
  "Industrial aggregate excluding unclassified businesses [11-91N]",                                                   
  "Goods producing industries [11-33N]",                                                                               
  "Forestry, logging and support [11N]",                                                                               
  "Forestry and logging [113]",                                                                                        
  "Timber tract operations [1131]",                                                                                    
  "Forest nurseries and gathering of forest products [1132]",                                                          
  "Logging [1133]",                                                                                                    
  "Support activities for forestry [1153]",                                                                            
  "Mining, quarrying, and oil and gas extraction [21]",                                                                
  "Oil and gas extraction [211,2111]",                                                                                 
  "Mining and quarrying (except oil and gas) [212]",                                                                   
  "Coal mining [2121]",                                                                                                
  "Metal ore mining [2122]",                                                                                           
  "Non-metallic mineral mining and quarrying [2123]",                                                                  
  "Support activities for mining, and oil and gas extraction [213,2131]",                                              
  "Utilities [22,221]",                                                                                                
  "Electric power generation, transmission and distribution [2211]",                                                   
  "Natural gas distribution [2212]",                                                                                   
  "Water, sewage and other systems [2213]",                                                                            
  "Construction [23]",                                                                                                 
  "Construction of buildings [236]",                                                                                   
  "Residential building construction [2361]",                                                                          
  "Non-residential building construction [2362]",                                                                      
  "Heavy and civil engineering construction [237]",                                                                    
  "Utility system construction [2371]",                                                                                
  "Land subdivision [2372]",                                                                                           
  "Highway, street and bridge construction [2373]",                                                                    
  "Other heavy and civil engineering construction [2379]",                                                             
  "Specialty trade contractors [238]",                                                                                 
  "Foundation, structure, and building exterior contractors [2381]",                                                   
  "Building equipment contractors [2382]",                                                                             
  "Building finishing contractors [2383]",                                                                             
  "Other specialty trade contractors [2389]",                                                                          
  "Manufacturing [31-33]",                                                                                             
  "Non-durable goods [311N]",                                                                                          
  "Food manufacturing [311]",                                                                                          
  "Animal food manufacturing [3111]",                                                                                  
  "Grain and oilseed milling [3112]",                                                                                  
  "Sugar and confectionery product manufacturing [3113]",                                                              
  "Fruit and vegetable preserving and specialty food manufacturing [3114]",                                            
  "Dairy product manufacturing [3115]",                                                                                
  "Meat product manufacturing [3116]",                                                                                 
  "Seafood product preparation and packaging [3117]",                                                                  
  "Bakeries and tortilla manufacturing [3118]",                                                                        
  "Other food manufacturing [3119]",                                                                                   
  "Beverage and tobacco product manufacturing [312]",                                                                  
  "Beverage manufacturing [3121]",                                                                                     
  "Tobacco manufacturing [3122]",                                                                                      
  "Cannabis product manufacturing [3123]",                                                                             
  "Textile mills [313]",                                                                                               
  "Fibre, yarn and thread mills [3131]",                                                                               
  "Fabric mills [3132]",                                                                                               
  "Textile and fabric finishing and fabric coating [3133]",                                                            
  "Textile product mills [314]",                                                                                       
  "Textile furnishings mills [3141]",                                                                                  
  "Other textile product mills [3149]",                                                                                
  "Clothing manufacturing [315]",                                                                                      
  "Clothing knitting mills [3151]",                                                                                    
  "Cut and sew clothing manufacturing [3152]",                                                                         
  "Clothing accessories and other clothing manufacturing [3159]",                                                      
  "Leather and allied product manufacturing [316]",                                                                    
  "Leather and hide tanning and finishing [3161]",                                                                     
  "Footwear manufacturing [3162]",                                                                                     
  "Other leather and allied product manufacturing [3169]",                                                             
  "Paper manufacturing [322]",                                                                                         
  "Pulp, paper and paperboard mills [3221]",                                                                           
  "Converted paper product manufacturing [3222]",                                                                      
  "Printing and related support activities [323,3231]",                                                                
  "Petroleum and coal product manufacturing [324,3241]",                                                               
  "Chemical manufacturing [325]",                                                                                      
  "Basic chemical manufacturing [3251]",                                                                               
  "Resin, synthetic rubber, and artificial and synthetic fibres and filaments manufacturing [3252]",                   
  "Pesticide, fertilizer and other agricultural chemical manufacturing [3253]",                                        
  "Pharmaceutical and medicine manufacturing [3254]",                                                                  
  "Paint, coating and adhesive manufacturing [3255]",                                                                  
  "Soap, cleaning compound and toilet preparation manufacturing [3256]",                                               
  "Other chemical product manufacturing [3259]",                                                                       
  "Plastics and rubber products manufacturing [326]",                                                                  
  "Plastic product manufacturing [3261]",                                                                              
  "Rubber product manufacturing [3262]",                                                                               
  "Durable goods [321N]",                                                                                              
  "Wood product manufacturing [321]",                                                                                  
  "Sawmills and wood preservation [3211]",                                                                             
  "Veneer, plywood and engineered wood product manufacturing [3212]",                                                  
  "Other wood product manufacturing [3219]",                                                                           
  "Non-metallic mineral product manufacturing [327]",                                                                  
  "Clay product and refractory manufacturing [3271]",                                                                  
  "Glass and glass product manufacturing [3272]",                                                                      
  "Cement and concrete product manufacturing [3273]",                                                                  
  "Lime and gypsum product manufacturing [3274]",                                                                      
  "Other non-metallic mineral product manufacturing [3279]",                                                           
  "Primary metal manufacturing [331]",                                                                                 
  "Iron and steel mills and ferro-alloy manufacturing [3311]",                                                         
  "Steel product manufacturing from purchased steel [3312]",                                                           
  "Alumina and aluminum production and processing [3313]",                                                             
  "Non-ferrous metal (except aluminum) production and processing [3314]",                                              
  "Foundries [3315]",                                                                                                  
  "Fabricated metal product manufacturing [332]",                                                                      
  "Forging and stamping [3321]",                                                                                       
  "Cutlery and hand tool manufacturing [3322]",                                                                        
  "Architectural and structural metals manufacturing [3323]",                                                          
  "Boiler, tank and shipping container manufacturing [3324]",                                                          
  "Hardware manufacturing [3325]",                                                                                     
  "Spring and wire product manufacturing [3326]",                                                                      
  "Machine shops, turned product, and screw, nut and bolt manufacturing [3327]",                                       
  "Coating, engraving, cold and heat treating and allied activities [3328]",                                           
  "Other fabricated metal product manufacturing [3329]",                                                               
  "Machinery manufacturing [333]",                                                                                     
  "Agricultural, construction and mining machinery manufacturing [3331]",                                              
  "Industrial machinery manufacturing [3332]",                                                                         
  "Commercial and service industry machinery manufacturing [3333]",                                                    
  "Ventilation, heating, air-conditioning and commercial refrigeration equipment manufacturing [3334]",                
  "Metalworking machinery manufacturing [3335]",                                                                       
  "Engine, turbine and power transmission equipment manufacturing [3336]",                                             
  "Other general-purpose machinery manufacturing [3339]",                                                              
  "Computer and electronic product manufacturing [334]",                                                               
  "Computer and peripheral equipment manufacturing [3341]",                                                            
  "Communications equipment manufacturing [3342]",                                                                     
  "Audio and video equipment manufacturing [3343]",                                                                    
  "Semiconductor and other electronic component manufacturing [3344]",                                                 
  "Navigational, measuring, medical and control instruments manufacturing [3345]",                                     
  "Manufacturing and reproducing magnetic and optical media [3346]",                                                   
  "Electrical equipment, appliance and component manufacturing [335]",                                                 
  "Electric lighting equipment manufacturing [3351]",                                                                  
  "Household appliance manufacturing [3352]",                                                                          
  "Electrical equipment manufacturing [3353]",                                                                         
  "Other electrical equipment and component manufacturing [3359]",                                                     
  "Transportation equipment manufacturing [336]",                                                                      
  "Motor vehicle manufacturing [3361]",                                                                                
  "Motor vehicle body and trailer manufacturing [3362]",                                                               
  "Motor vehicle parts manufacturing [3363]",                                                                          
  "Aerospace product and parts manufacturing [3364]",                                                                  
  "Railroad rolling stock manufacturing [3365]",                                                                       
  "Ship and boat building [3366]",                                                                                     
  "Other transportation equipment manufacturing [3369]",                                                               
  "Furniture and related product manufacturing [337]",                                                                 
  "Household and institutional furniture and kitchen cabinet manufacturing [3371]",                                    
  "Office furniture (including fixtures) manufacturing [3372]",                                                        
  "Other furniture-related product manufacturing [3379]",                                                              
  "Miscellaneous manufacturing [339]",                                                                                 
  "Medical equipment and supplies manufacturing [3391]",                                                               
  "Other miscellaneous manufacturing [3399]",                                                                          
  "Service producing industries [41-91N]",                                                                             
  "Trade [41-45N]",                                                                                                    
  "Wholesale trade [41]",                                                                                              
  "Farm product merchant wholesalers [411,4111]",                                                                      
  "Petroleum and petroleum products merchant wholesalers [412,4121]",                                                  
  "Food, beverage and tobacco merchant wholesalers [413]",                                                             
  "Food merchant wholesalers [4131]",                                                                                  
  "Beverage merchant wholesalers [4132]",                                                                              
  "Cigarette and tobacco product merchant wholesalers [4133]",                                                         
  "Cannabis merchant wholesalers [4134]",                                                                              
  "Personal and household goods merchant wholesalers [414]",                                                           
  "Textile, clothing and footwear merchant wholesalers [4141]",                                                        
  "Home entertainment equipment and household appliance merchant wholesalers [4142]",                                  
  "Home furnishings merchant wholesalers [4143]",                                                                      
  "Personal goods merchant wholesalers [4144]",                                                                        
  "Pharmaceuticals, toiletries, cosmetics and sundries merchant wholesalers [4145]",                                   
  "Motor vehicle and motor vehicle parts and accessories merchant wholesalers [415]",                                  
  "Motor vehicle merchant wholesalers [4151]",                                                                         
  "New motor vehicle parts and accessories merchant wholesalers [4152]",                                               
  "Used motor vehicle parts and accessories merchant wholesalers [4153]",                                              
  "Building material and supplies merchant wholesalers [416]",                                                         
  "Electrical, plumbing, heating and air-conditioning equipment and supplies merchant wholesalers [4161]",             
  "Metal service centres [4162]",                                                                                      
  "Lumber, millwork, hardware and other building supplies merchant wholesalers [4163]",                                
  "Machinery, equipment and supplies merchant wholesalers [417]",                                                      
  "Farm, lawn and garden machinery and equipment merchant wholesalers [4171]",                                         
  "Construction, forestry, mining, and industrial machinery, equipment and supplies merchant wholesalers [4172]",      
  "Computer and communications equipment and supplies merchant wholesalers [4173]",                                    
  "Other machinery, equipment and supplies merchant wholesalers [4179]",                                               
  "Miscellaneous merchant wholesalers [418]",                                                                          
  "Recyclable material merchant wholesalers [4181]",                                                                   
  "Paper, paper product and disposable plastic product merchant wholesalers [4182]",                                   
  "Agricultural supplies merchant wholesalers [4183]",                                                                 
  "Chemical (except agricultural) and allied product merchant wholesalers [4184]",                                     
  "Other miscellaneous merchant wholesalers [4189]",                                                                   
  "Business-to-business electronic markets, and agents and brokers [419,4191]",                                        
  "Retail trade [44-45]",                                                                                              
  "Motor vehicle and parts dealers [441]",                                                                             
  "Automobile dealers [4411]",                                                                                         
  "Other motor vehicle dealers [4412]",                                                                                
  "Automotive parts, accessories and tire stores [4413]",                                                              
  "Furniture and home furnishings stores [442]",                                                                       
  "Furniture stores [4421]",                                                                                           
  "Home furnishings stores [4422]",                                                                                    
  "Electronics and appliance stores [443,4431]",                                                                      
  "Building material and garden equipment and supplies dealers [444]",                                                 
  "Building material and supplies dealers [4441]",                                                                     
  "Lawn and garden equipment and supplies stores [4442]",                                                              
  "Food and beverage stores [445]",                                                                                    
  "Grocery stores [4451]",                                                                                             
  "Specialty food stores [4452]",                                                                                      
  "Beer, wine and liquor stores [4453]",                                                                               
  "Health and personal care stores [446,4461]",                                                                        
  "Gasoline stations [447,4471]",                                                                                      
  "Clothing and clothing accessories stores [448]",                                                                    
  "Clothing stores [4481]",                                                                                            
  "Shoe stores [4482]",                                                                                                
  "Jewellery, luggage and leather goods stores [4483]",                                                                
  "Sporting goods, hobby, book and music stores [451]",                                                                
  "Sporting goods, hobby and musical instrument stores [4511]",                                                        
  "Book, periodical and music stores [4512]",                                                                          
  "Book stores and news dealers [4513]",                                                                               
  "General merchandise stores [452]",                                                                                  
  "Department stores [4521]",                                                                                          
  "Other general merchandise stores [4529]",                                                                           
  "Miscellaneous store retailers [453]",                                                                               
  "Florists [4531]",                                                                                                   
  "Office supplies, stationery and gift stores [4532]",                                                                
  "Used merchandise stores [4533]",                                                                                    
  "Other miscellaneous store retailers [4539]",                                                                        
  "Non-store retailers [454]",                                                                                         
  "Electronic shopping and mail-order houses [4541]",                                                                  
  "Vending machine operators [4542]",                                                                                  
  "Direct selling establishments [4543]",                                                                              
  "Transportation and warehousing [48-49]",                                                                            
  "Air transportation [481]",                                                                                          
  "Scheduled air transportation [4811]",                                                                               
  "Non-scheduled air transportation [4812]",                                                                           
  "Rail transportation [482,4821]",                                                                                    
  "Water transportation [483]",                                                                                        
  "Deep sea, coastal and Great Lakes water transportation [4831]",                                                     
  "Truck transportation [484]",                                                                                        
  "General freight trucking [4841]",                                                                                   
  "Specialized freight trucking [4842]",                                                                               
  "Transit and ground passenger transportation [485]",                                                                
  "Urban transit systems [4851]",                                                                                      
  "Interurban and rural bus transportation [4852]",                                                                    
  "Taxi and limousine service [4853]",                                                                                 
  "School and employee bus transportation [4854]",                                                                     
  "Charter bus industry [4855]",                                                                                       
  "Other transit and ground passenger transportation [4859]",                                                          
  "Pipeline transportation [486]",                                                                                     
  "Pipeline transportation of crude oil [4861]",                                                                       
  "Scenic and sightseeing transportation [487]",                                                                       
  "Scenic and sightseeing transportation, water [4872]",                                                               
  "Support activities for transportation [488]",                                                                       
  "Support activities for air transportation [4881]",                                                                  
  "Support activities for rail transportation [4882]",                                                                 
  "Support activities for water transportation [4883]",                                                                
  "Support activities for road transportation [4884]",                                                                 
  "Freight transportation arrangement [4885]",                                                                         
  "Other support activities for transportation [4889]",                                                                
  "Couriers and messengers [492]",                                                                                     
  "Couriers [4921]",                                                                                                   
  "Local messengers and local delivery [4922]",                                                                        
  "Warehousing and storage [493, 4931]",                                                                               
  "Information and cultural industries [51]",                                                                          
  "Publishing industries [511]",                                                                                       
  "Newspaper, periodical, book and directory publishers [5111]",                                                       
  "Software publishers [5112]",                                                                                        
  "Motion picture and sound recording industries [512]",                                                               
  "Motion picture and video industries [5121]",                                                                        
  "Sound recording industries [5122]",                                                                                 
  "Broadcasting (except Internet) [515]",                                                                              
  "Radio and television broadcasting [5151]",                                                                          
  "Pay and specialty television [5152]",                                                                               
  "Telecommunications [517]",                                                                                          
  "Wired telecommunications carriers [5171]",                                                                          
  "Wireless telecommunications carriers (except satellite) [5172]",                                                    
  "Wired and wireless telecommunications carriers (except satellite) [5173]",                                          
  "Satellite telecommunications [5174]",                                                                               
  "Other telecommunications [5179]",                                                                                   
  "Data processing, hosting, and related services [518,5182]",                                                         
  "Other information services [519,5191]",                                                                             
  "Finance and insurance [52]",                                                                                        
  "Credit intermediation and related activities [522]",                                                                
  "Depository credit intermediation [5221]",                                                                           
  "Non-depository credit intermediation [5222]",                                                                       
  "Activities related to credit intermediation [5223]",                                                                
  "Securities, commodity contracts, and other financial investment and related activities [523]",                      
  "Securities and commodity contracts intermediation and brokerage [5231]",                                            
  "Securities and commodity exchanges [5232]",                                                                         
  "Other financial investment activities [5239]",                                                                      
  "Insurance carriers and related activities [524]",                                                                   
  "Insurance carriers [5241]",                                                                                         
  "Agencies, brokerages and other insurance related activities [5242]",                                                
  "Real estate and rental and leasing [53]",                                                                           
  "Real estate [531]",                                                                                                 
  "Lessors of real estate [5311]",                                                                                     
  "Offices of real estate agents and brokers [5312]",                                                                  
  "Activities related to real estate [5313]",                                                                          
  "Rental and leasing services [532]",                                                                                 
  "Automotive equipment rental and leasing [5321]",                                                                    
  "Consumer goods rental [5322]",                                                                                      
  "General rental centres [5323]",                                                                                     
  "Commercial and industrial machinery and equipment rental and leasing [5324]",                                       
  "Lessors of non-financial intangible assets (except copyrighted works) [533,5331]",                                  
  "Professional, scientific and technical services [54,541]",                                                          
  "Legal services [5411]",                                                                                             
  "Accounting, tax preparation, bookkeeping and payroll services [5412]",                                              
  "Architectural, engineering and related services [5413]",                                                            
  "Specialized design services [5414]",                                                                                
  "Computer systems design and related services [5415]",                                                               
  "Management, scientific and technical consulting services [5416]",                                                   
  "Scientific research and development services [5417]",                                                               
  "Advertising, public relations, and related services [5418]",                                                        
  "Other professional, scientific and technical services [5419]",                                                      
  "Management of companies and enterprises [55,551,5511]",                                                             
  "Administrative and support, waste management and remediation services [56]",                                        
  "Administrative and support services [561]",                                                                         
  "Office administrative services [5611]",                                                                             
  "Employment services [5613]",                                                                                        
  "Business support services [5614]",                                                                                  
  "Travel arrangement and reservation services [5615]",                                                                
  "Investigation and security services [5616]",                                                                        
  "Services to buildings and dwellings [5617]",                                                                        
  "Other support services [5619]",                                                                                     
  "Waste management and remediation services [562]",                                                                   
  "Waste collection [5621]",                                                                                           
  "Waste treatment and disposal [5622]",                                                                               
  "Remediation and other waste management services [5629]",                                                            
  "Educational services [61,611]",                                                                                     
  "Education special [611N]",                                                                                          
  "Elementary and secondary schools [6111]",                                                                          
  "Community colleges and C.E.G.E.P.s [6112]",                                                                         
  "Universities [6113]",                                                                                               
  "Business schools and computer and management training [6114]",                                                      
  "Technical and trade schools [6115]",                                                                                
  "Other schools and instruction [6116]",                                                                              
  "Educational support services [6117]",                                                                               
  "Health care and social assistance [62]",                                                                            
  "Ambulatory health care services [621]",                                                                             
  "Offices of physicians [6211]",                                                                                      
  "Offices of dentists [6212]",                                                                                        
  "Offices of other health practitioners [6213]",                                                                      
  "Out-patient care centres [6214]",                                                                                   
  "Medical and diagnostic laboratories [6215]",                                                                        
  "Home health care services [6216]",                                                                                  
  "Other ambulatory health care services [6219]",                                                                      
  "Hospitals [622]",                                                                                                   
  "General medical and surgical hospitals [6221]",                                                                     
  "Psychiatric and substance abuse hospitals [6222]",                                                                  
  "Specialty (except psychiatric and substance abuse) hospitals [6223]",                                               
  "Nursing and residential care facilities [623]",                                                                     
  "Nursing care facilities [6231]",                                                                                    
  "Residential developmental handicap, mental health and substance abuse facilities [6232]",                           
  "Community care facilities for the elderly [6233]",                                                                  
  "Other residential care facilities [6239]",                                                                          
  "Social assistance [624]",                                                                                           
  "Individual and family services [6241]",                                                                             
  "Community food and housing, and emergency and other relief services [6242]",                                        
  "Vocational rehabilitation services [6243]",                                                                         
  "Child day-care services [6244]",                                                                                    
  "Arts, entertainment and recreation [71]",                                                                           
  "Performing arts, spectator sports and related industries [711]",                                                    
  "Performing arts companies [7111]",                                                                                  
  "Spectator sports [7112]",                                                                                           
  "Promoters (presenters) of performing arts, sports and similar events [7113]",                                       
  "Agents and managers for artists, athletes, entertainers and other public figures [7114]",                           
  "Independent artists, writers and performers [7115]",                                                                
  "Heritage institutions [712,7121]",                                                                                  
  "Amusement, gambling and recreation industries [713]",                                                               
  "Amusement parks and arcades [7131]",                                                                                
  "Gambling industries [7132]",                                                                                        
  "Other amusement and recreation industries [7139]",                                                                  
  "Accommodation and food services [72]",                                                                              
  "Accommodation services [721]",                                                                                      
  "Traveller accommodation [7211]",                                                                                    
  "Recreational vehicle (RV) parks and recreational camps [7212]",                                                     
  "Rooming and boarding houses [7213]",                                                                                
  "Food services and drinking places [722]",                                                                           
  "Full-service restaurants [7221]",                                                                                   
  "Limited-service eating places [7222]",                                                                              
  "Special food services [7223]",                                                                                      
  "Drinking places (alcoholic beverages) [7224]",                                                                      
  "Full-service restaurants and limited-service eating places [7225]",                                                 
  "Other services (except public administration) [81]",                                                                
  "Repair and maintenance [811]",                                                                                      
  "Automotive repair and maintenance [8111]",                                                                          
  "Electronic and precision equipment repair and maintenance [8112]",                                                  
  "Commercial and industrial machinery and equipment (except automotive and electronic) repair and maintenance [8113]",
  "Personal and household goods repair and maintenance [8114]",                                                        
  "Personal and laundry services [812]",                                                                               
  "Personal care services [8121]",                                                                                     
  "Funeral services [8122]",                                                                                           
  "Dry cleaning and laundry services [8123]",                                                                          
  "Other personal services [8129]",                                                                                    
  "Religious, grant-making, civic, and professional and similar organizations [813]",                                  
  "Grant-making and giving services [8132]",                                                                           
  "Social advocacy organizations [8133]",                                                                              
  "Civic and social organizations [8134]",                                                                            
  "Business, professional, labour and other membership organizations [8139]",                                          
  "Public administration [91]",                                                                                        
  "Federal government public administration [911]",                                                                    
  "Provincial and territorial public administration [912]",                                                            
  "Local, municipal and regional public administration [913]",                                                         
  "Aboriginal public administration [914]",                                                                            
  "Unclassified businesses [00]",                                                                                      
  "Facilities support services [5612]"                                                                                
)
trf1001 <- c(
  "Original data (no transformation)",
  "Including trend line",
  "Index, first month = 100",
  "One-month percentage change",
  "Twelve-month percentage change"
)
e <- seq.Date(TS[[7]]$Strt,TS[[7]]$Endt,by="month")
s <- character()
for (i in 1:length(e)) {
  s[i] <- format(e[i],"%b %Y")
}
r <- c(s[length(s)-5],s[length(s)])

mc07UI <- function(id) {
  tabPanel(tags$b(tags$span(style="color:blue", HTML("Charts"))),
    prettyRadioButtons(NS(id,"Est"),
      tags$b(tags$span(style="color:blue;font-size:20px", 
      "Employment or average weekly earnings:")),choices=Est1001,bigger=TRUE,
      outline=TRUE,inline=TRUE,shape="round",animation="pulse"),
    tags$style(HTML(".selectize-input, .option {color:blue;font-size:20px}")),   
    selectInput(NS(id,"naics"),
      label=tags$b(tags$span(style="color:blue; font-size:20px",
      "Choose an industry:")),choices=naics1001,width = "100%"),
    fluidRow(column(5,
      prettyRadioButtons(NS(id,"trf"),
        tags$b(tags$span(style="color:blue;font-size:20px", 
        "Choose a transformation:")),choices=trf1001,bigger=TRUE,
        outline=TRUE,inline=TRUE,shape="round",animation="pulse")),
      column(5,textInput(NS(id,"altTitl"),
        tags$b(tags$span(style="color:blue;font-size:20px",
          "Choose your own chart title (optional):")),
          value="",width="90%")),
      column(2,downloadButton(NS(id,"downloadData1"),label="Download chart"))
    ),
    chooseSliderSkin(skin="Round",color="blue"),
    sliderTextInput(NS(id,"Dates"),label= 
      "Choose starting and ending dates:",
      choices=s,
      selected=r,
      dragRange = TRUE,
      width="100%"),
    tags$script(HTML(
      "$('.shiny-input-container:has(input[id=\"idmc07-Dates\"])>label')
      .css({ffontWeight:900,fontSize:'20px',color:'blue'})")),
    plotOutput(NS(id,"chart")) 
  )
}
mc07Server <- function(id) {
  moduleServer(id,function(input,output,session) {
    q0 <- readRDS(paste0("rds/",TS[[7]]$STCno,".rds"))
    Est2  <- reactive({input$Est})
    naics2  <- reactive({input$naics})
    type2 <- reactive(case_when(
      input$trf=="Original data (no transformation)"~1,
      input$trf=="Including trend line"~2,
      input$trf=="Index, first month = 100"~3,
      input$trf=="One-month percentage change"~4,
      input$trf=="Twelve-month percentage change"~5
    ))    
    month1 <- reactive({
      as.Date(paste0(substr(input$Dates[1],1,3)," 1, ",
        substr(input$Dates[1],5,8)),format("%b %d, %Y"))
    })
    month2 <- reactive({
      as.Date(paste0(substr(input$Dates[2],1,3)," 1, ",
        substr(input$Dates[2],5,8)),format("%b %d, %Y"))
    })
    altTitle <- reactive({input$altTitl})
    chartP <- reactive({ Make_chrtM07(naics2(),Est2(),type2(),
        month1(),month2(),altTitle(),"") })
    output$chart <- renderPlot({chartP()},height=700)
    output$downloadData1 <- downloadHandler(
      filename=function() {
        paste0("Employment_and_AWE.png")
      },
      content=function(file) {
        ggsave(file,chartP(),height=8,width=14,dpi=300)
      }
    )
    observe({
      r <- c(s[length(s)-25],s[length(s)])
      updateSliderTextInput(session,inputId="Dates",
        label="Choose starting and ending dates:",
        choices=s,
        selected=r)
      tags$script(HTML(
        "$('.shiny-input-container:has(input[id=\"idmc07-Dates\"])>label')
        .css({fontWeight:900,fontSize:'20px',color:'blue'})"))
    })
    observeEvent(input$Est,
      updateSelectInput(session,"naics",label="Choose an industry:",
        choices=unique(filter(q0,EST==input$Est)$NAICS))
    )
  })
}

